# fly.toml app configuration file generated for url-shortener-3b7-eg on 2025-02-20T16:40:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'url-shortener-3b7-eg'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
